import { IngredientInfo } from '../types';

export const INGREDIENTS_DATA: IngredientInfo[] = [
  {
    id: 'niacinamide',
    name: 'Niacinamide (Vitamin B3)',
    category: 'Barrier & Tone Support',
    whatItDoes: 'Helps balance surface sebum production, strengthens the skin moisture barrier, and improves the appearance of uneven skin tone.',
    bestFor: 'Oily T-zones, enlarged pores, and post-blemish marks.',
    howToUse: 'Suitable for daily morning and evening application. Pairs seamlessly with salicylic acid and hyaluronic acid.',
    scientificInsight: 'Niacinamide acts as a precursor to essential cellular co-enzymes (NAD/NADP), aiding natural ceramide biosynthesis in the epidermis.',
    matchedProducts: ['aegis-clear', 'aegis-shield']
  },
  {
    id: 'salicylic-acid',
    name: 'Salicylic Acid (BHA)',
    category: 'Lipophilic Exfoliant',
    whatItDoes: 'An oil-soluble beta-hydroxy acid that penetrates inside pores to loosen trapped sebum, dead skin cells, and debris.',
    bestFor: 'Blackheads, congested pores, breakouts, and ingrown hairs.',
    howToUse: 'Apply 2-3 drops after cleansing. Can be used daily or 3-4 times a week depending on skin tolerance.',
    scientificInsight: 'Because salicylic acid is oil-soluble, it can dissolve the intercellular lipid glue holding keratin plugs together inside sebaceous follicles.',
    matchedProducts: ['aegis-clear', 'aegis-wash']
  },
  {
    id: 'ceramides',
    name: '3:1:1 Biomimetic Ceramides',
    category: 'Barrier Repair Lipids',
    whatItDoes: 'Replenishes the intercellular lipid matrix to prevent transepidermal water loss and protect against shaving irritation.',
    bestFor: 'Dryness, post-shave sensitivity, tightness, and compromised skin barriers.',
    howToUse: 'Apply as a fluid moisturizer after serums or directly post-shave to soothe and rebuild.',
    scientificInsight: 'The human stratum corneum is composed of ceramides, cholesterol, and free fatty acids in an approximate 3:1:1 physiological ratio for optimal lipid lamellar stacking.',
    matchedProducts: ['aegis-barrier']
  },
  {
    id: 'hyaluronic-polyglutamic',
    name: 'Polyglutamic & Hyaluronic Acid',
    category: 'Multi-Depth Hydration',
    whatItDoes: 'Draws moisture into the upper and deeper layers of the epidermis, creating a smooth, supple, non-sticky surface.',
    bestFor: 'Dehydration, dullness, and skin feeling tight after showers.',
    howToUse: 'Formulated directly into serums and fluid emulsions for effortless daily hydration.',
    scientificInsight: 'Polyglutamic acid forms a flexible micro-film on the surface that holds moisture while supporting the deeper water-binding properties of hyaluronic acid.',
    matchedProducts: ['aegis-barrier', 'aegis-clear']
  },
  {
    id: 'ectoin',
    name: 'Ectoin (1.0%)',
    category: 'Extremolyte Cellular Shield',
    whatItDoes: 'A natural extremolyte molecule that protects skin cells against environmental stressors, heat, urban pollution, and HEV blue light.',
    bestFor: 'Daily outdoor commuting, screen exposure, and urban defense.',
    howToUse: 'Included in daily sunscreen and barrier formulas for all-day ambient protection.',
    scientificInsight: 'Discovered in micro-organisms surviving in extreme desert environments, ectoin forms a protective hydration shell around cellular proteins and membranes.',
    matchedProducts: ['aegis-shield']
  },
  {
    id: 'zinc-pca',
    name: 'Zinc PCA (1.0%)',
    category: 'Purifying & Calming Mineral',
    whatItDoes: 'Helps regulate surface sebum levels while calming inflammation and supporting a balanced skin microbiome.',
    bestFor: 'Excess shine, breakout-prone skin, and post-shave bumps.',
    howToUse: 'Combined with niacinamide and BHA in lightweight water-based serums.',
    scientificInsight: 'PCA (Pyrrolidone Carboxylic Acid) is an endogenous component of natural moisturizing factors (NMF), enhancing the bioavailability of elemental zinc.',
    matchedProducts: ['aegis-clear']
  },
  {
    id: 'apple-amino-acids',
    name: 'Apple Amino Acid Surfactants',
    category: 'Biomimetic Cleansing',
    whatItDoes: 'Cleanses gently by creating a dense, soft foam that lifts dirt and oil without stripping essential natural barrier lipids.',
    bestFor: 'All skin types, especially skin prone to tightness after cleansing.',
    howToUse: 'Used as the primary cleansing agent in AEGIS WASH at physiological pH 5.5.',
    scientificInsight: 'Derived from essential amino acids, these surfactants maintain the acid mantle integrity and avoid protein denaturation in the stratum corneum.',
    matchedProducts: ['aegis-wash']
  },
  {
    id: 'green-tea-egcg',
    name: 'Green Tea EGCG Polyphenols',
    category: 'Antioxidant & Calming',
    whatItDoes: 'Neutralizes free radicals generated by UV light and pollution while soothing skin irritation and redness.',
    bestFor: 'Redness, environmental exposure, and post-shave comfort.',
    howToUse: 'Present in cleansers and daily sunscreen for continuous soothing.',
    scientificInsight: 'Epigallocatechin gallate (EGCG) is one of nature’s most potent plant polyphenols, helping mitigate oxidative lipid peroxidation.',
    matchedProducts: ['aegis-wash', 'aegis-shield']
  }
];
